"""empty message

Revision ID: 1bec10466532
Revises: None
Create Date: 2015-12-04 07:11:14.119756

"""

# revision identifiers, used by Alembic.
revision = '1bec10466532'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('door', sa.Column('password', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('door', 'password')
    ### end Alembic commands ###
