"""empty message

Revision ID: 296a9288bc8e
Revises: 1c98d63b6508
Create Date: 2016-02-19 14:10:58.055152

"""

# revision identifiers, used by Alembic.
revision = '296a9288bc8e'
down_revision = '1c98d63b6508'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('monthlyAccessAverage', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('monthlyAccessCount', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('monthlyAccessMonthNumber', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('weeklyAccessAverage', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('weeklyAccessCount', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('weeklyAccessWeekNumber', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weeklyAccessWeekNumber')
    op.drop_column('user', 'weeklyAccessCount')
    op.drop_column('user', 'weeklyAccessAverage')
    op.drop_column('user', 'monthlyAccessMonthNumber')
    op.drop_column('user', 'monthlyAccessCount')
    op.drop_column('user', 'monthlyAccessAverage')
    ### end Alembic commands ###
