"""empty message

Revision ID: 31b5bd80b4ea
Revises: 296a9288bc8e
Create Date: 2016-02-25 07:45:43.379435

"""

# revision identifiers, used by Alembic.
revision = '31b5bd80b4ea'
down_revision = '296a9288bc8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('statistic', sa.Column('displayConfig', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'displayConfig')
    op.drop_column('statistic', 'description')
    ### end Alembic commands ###
