"""Add statistic and statisticEntry tables

Revision ID: 4a5c5d68e81e
Revises: None
Create Date: 2016-02-08 07:15:14.998677

"""

# revision identifiers, used by Alembic.
revision = '4a5c5d68e81e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('statId', sa.Integer(), nullable=True),
    sa.Column('statType', sa.Integer(), nullable=True),
    sa.Column('binningCount', sa.Integer(), nullable=True),
    sa.Column('seriesCount', sa.Integer(), nullable=True),
    sa.Column('seriesName1', sa.Text(), nullable=True),
    sa.Column('seriesName2', sa.Text(), nullable=True),
    sa.Column('seriesName3', sa.Text(), nullable=True),
    sa.Column('seriesName4', sa.Text(), nullable=True),
    sa.Column('seriesName5', sa.Text(), nullable=True),
    sa.Column('seriesName6', sa.Text(), nullable=True),
    sa.Column('seriesName7', sa.Text(), nullable=True),
    sa.Column('seriesName8', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statId', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('binningId', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic_entry')
    op.drop_table('statistic')
    ### end Alembic commands ###
